### ISSUE TITLE
Needs Update For PHP7

### ISSUE THREAD

**Issue by ukmerlin** [sriniguna/quotes-collection#8]
Hi, I cannot update my WP site due to this plugins incompatibility with PHP. Are you planning an update? Ta!

**Comment by lwitzel** [comment]
I have it running without trouble on PHP 7.3. What is the specific error you're seeing?

**Comment by ukmerlin** [comment]
Hmm. I forced an update to the latest WP and reactivated this plug in and it seems to work regardless. Thank you. Unfortunately I did not download the original compatibility report that showed the lines causing problems..
